pub mod auth;
pub mod cluster;
pub mod database;
pub mod docs;
pub mod insert;
pub mod keys;
pub mod logs;
pub mod open;
pub mod organization;
pub mod ping;
pub mod query;
pub mod status;
pub mod table;
mod table_output;
